// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: sidecar.proto

package sidecar

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Authentication metadata
type RequestMetadata struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	RequestId          string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	EphemeralToken     string                 `protobuf:"bytes,2,opt,name=ephemeral_token,json=ephemeralToken,proto3" json:"ephemeral_token,omitempty"`
	TimestampUnix      int64                  `protobuf:"varint,3,opt,name=timestamp_unix,json=timestampUnix,proto3" json:"timestamp_unix,omitempty"`
	OperationSignature string                 `protobuf:"bytes,4,opt,name=operation_signature,json=operationSignature,proto3" json:"operation_signature,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RequestMetadata) Reset() {
	*x = RequestMetadata{}
	mi := &file_sidecar_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestMetadata) ProtoMessage() {}

func (x *RequestMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_sidecar_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestMetadata.ProtoReflect.Descriptor instead.
func (*RequestMetadata) Descriptor() ([]byte, []int) {
	return file_sidecar_proto_rawDescGZIP(), []int{0}
}

func (x *RequestMetadata) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RequestMetadata) GetEphemeralToken() string {
	if x != nil {
		return x.EphemeralToken
	}
	return ""
}

func (x *RequestMetadata) GetTimestampUnix() int64 {
	if x != nil {
		return x.TimestampUnix
	}
	return 0
}

func (x *RequestMetadata) GetOperationSignature() string {
	if x != nil {
		return x.OperationSignature
	}
	return ""
}

// Health check
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_sidecar_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sidecar_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_sidecar_proto_rawDescGZIP(), []int{1}
}

type HealthCheckResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Status          string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	UptimeSeconds   int64                  `protobuf:"varint,2,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	ActiveRequests  int32                  `protobuf:"varint,3,opt,name=active_requests,json=activeRequests,proto3" json:"active_requests,omitempty"`
	MemoryUsedBytes int64                  `protobuf:"varint,4,opt,name=memory_used_bytes,json=memoryUsedBytes,proto3" json:"memory_used_bytes,omitempty"`
	Version         string                 `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_sidecar_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sidecar_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_sidecar_proto_rawDescGZIP(), []int{2}
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthCheckResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *HealthCheckResponse) GetActiveRequests() int32 {
	if x != nil {
		return x.ActiveRequests
	}
	return 0
}

func (x *HealthCheckResponse) GetMemoryUsedBytes() int64 {
	if x != nil {
		return x.MemoryUsedBytes
	}
	return 0
}

func (x *HealthCheckResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// Storage messages
type UploadBlobRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Metadata       *RequestMetadata       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Provider       string                 `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	DestinationUri string                 `protobuf:"bytes,3,opt,name=destination_uri,json=destinationUri,proto3" json:"destination_uri,omitempty"`
	ContentType    string                 `protobuf:"bytes,4,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	ProviderConfig map[string]string      `protobuf:"bytes,5,rep,name=provider_config,json=providerConfig,proto3" json:"provider_config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Content        []byte                 `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	LocalFilePath  string                 `protobuf:"bytes,7,opt,name=local_file_path,json=localFilePath,proto3" json:"local_file_path,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UploadBlobRequest) Reset() {
	*x = UploadBlobRequest{}
	mi := &file_sidecar_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadBlobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadBlobRequest) ProtoMessage() {}

func (x *UploadBlobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sidecar_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadBlobRequest.ProtoReflect.Descriptor instead.
func (*UploadBlobRequest) Descriptor() ([]byte, []int) {
	return file_sidecar_proto_rawDescGZIP(), []int{3}
}

func (x *UploadBlobRequest) GetMetadata() *RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *UploadBlobRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *UploadBlobRequest) GetDestinationUri() string {
	if x != nil {
		return x.DestinationUri
	}
	return ""
}

func (x *UploadBlobRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *UploadBlobRequest) GetProviderConfig() map[string]string {
	if x != nil {
		return x.ProviderConfig
	}
	return nil
}

func (x *UploadBlobRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *UploadBlobRequest) GetLocalFilePath() string {
	if x != nil {
		return x.LocalFilePath
	}
	return ""
}

type UploadBlobResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	BlobId            string                 `protobuf:"bytes,1,opt,name=blob_id,json=blobId,proto3" json:"blob_id,omitempty"`
	Etag              string                 `protobuf:"bytes,2,opt,name=etag,proto3" json:"etag,omitempty"`
	SizeBytes         int64                  `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	ContentHashSha256 string                 `protobuf:"bytes,4,opt,name=content_hash_sha256,json=contentHashSha256,proto3" json:"content_hash_sha256,omitempty"`
	TimestampUnix     int64                  `protobuf:"varint,5,opt,name=timestamp_unix,json=timestampUnix,proto3" json:"timestamp_unix,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UploadBlobResponse) Reset() {
	*x = UploadBlobResponse{}
	mi := &file_sidecar_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadBlobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadBlobResponse) ProtoMessage() {}

func (x *UploadBlobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sidecar_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadBlobResponse.ProtoReflect.Descriptor instead.
func (*UploadBlobResponse) Descriptor() ([]byte, []int) {
	return file_sidecar_proto_rawDescGZIP(), []int{4}
}

func (x *UploadBlobResponse) GetBlobId() string {
	if x != nil {
		return x.BlobId
	}
	return ""
}

func (x *UploadBlobResponse) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

func (x *UploadBlobResponse) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *UploadBlobResponse) GetContentHashSha256() string {
	if x != nil {
		return x.ContentHashSha256
	}
	return ""
}

func (x *UploadBlobResponse) GetTimestampUnix() int64 {
	if x != nil {
		return x.TimestampUnix
	}
	return 0
}

type DownloadBlobRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Metadata       *RequestMetadata       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Provider       string                 `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	SourceUri      string                 `protobuf:"bytes,3,opt,name=source_uri,json=sourceUri,proto3" json:"source_uri,omitempty"`
	ProviderConfig map[string]string      `protobuf:"bytes,4,rep,name=provider_config,json=providerConfig,proto3" json:"provider_config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	OffsetBytes    int64                  `protobuf:"varint,5,opt,name=offset_bytes,json=offsetBytes,proto3" json:"offset_bytes,omitempty"`
	MaxBytes       int64                  `protobuf:"varint,6,opt,name=max_bytes,json=maxBytes,proto3" json:"max_bytes,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DownloadBlobRequest) Reset() {
	*x = DownloadBlobRequest{}
	mi := &file_sidecar_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadBlobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadBlobRequest) ProtoMessage() {}

func (x *DownloadBlobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sidecar_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadBlobRequest.ProtoReflect.Descriptor instead.
func (*DownloadBlobRequest) Descriptor() ([]byte, []int) {
	return file_sidecar_proto_rawDescGZIP(), []int{5}
}

func (x *DownloadBlobRequest) GetMetadata() *RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *DownloadBlobRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *DownloadBlobRequest) GetSourceUri() string {
	if x != nil {
		return x.SourceUri
	}
	return ""
}

func (x *DownloadBlobRequest) GetProviderConfig() map[string]string {
	if x != nil {
		return x.ProviderConfig
	}
	return nil
}

func (x *DownloadBlobRequest) GetOffsetBytes() int64 {
	if x != nil {
		return x.OffsetBytes
	}
	return 0
}

func (x *DownloadBlobRequest) GetMaxBytes() int64 {
	if x != nil {
		return x.MaxBytes
	}
	return 0
}

type BlobChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	IsLast        bool                   `protobuf:"varint,3,opt,name=is_last,json=isLast,proto3" json:"is_last,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlobChunk) Reset() {
	*x = BlobChunk{}
	mi := &file_sidecar_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlobChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlobChunk) ProtoMessage() {}

func (x *BlobChunk) ProtoReflect() protoreflect.Message {
	mi := &file_sidecar_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlobChunk.ProtoReflect.Descriptor instead.
func (*BlobChunk) Descriptor() ([]byte, []int) {
	return file_sidecar_proto_rawDescGZIP(), []int{6}
}

func (x *BlobChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *BlobChunk) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *BlobChunk) GetIsLast() bool {
	if x != nil {
		return x.IsLast
	}
	return false
}

type ListBlobsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Metadata       *RequestMetadata       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Provider       string                 `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	Prefix         string                 `protobuf:"bytes,3,opt,name=prefix,proto3" json:"prefix,omitempty"`
	MaxResults     int32                  `protobuf:"varint,4,opt,name=max_results,json=maxResults,proto3" json:"max_results,omitempty"`
	ProviderConfig map[string]string      `protobuf:"bytes,5,rep,name=provider_config,json=providerConfig,proto3" json:"provider_config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListBlobsRequest) Reset() {
	*x = ListBlobsRequest{}
	mi := &file_sidecar_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBlobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBlobsRequest) ProtoMessage() {}

func (x *ListBlobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sidecar_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBlobsRequest.ProtoReflect.Descriptor instead.
func (*ListBlobsRequest) Descriptor() ([]byte, []int) {
	return file_sidecar_proto_rawDescGZIP(), []int{7}
}

func (x *ListBlobsRequest) GetMetadata() *RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ListBlobsRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *ListBlobsRequest) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *ListBlobsRequest) GetMaxResults() int32 {
	if x != nil {
		return x.MaxResults
	}
	return 0
}

func (x *ListBlobsRequest) GetProviderConfig() map[string]string {
	if x != nil {
		return x.ProviderConfig
	}
	return nil
}

type ListBlobsResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Blobs             []*BlobInfo            `protobuf:"bytes,1,rep,name=blobs,proto3" json:"blobs,omitempty"`
	ContinuationToken string                 `protobuf:"bytes,2,opt,name=continuation_token,json=continuationToken,proto3" json:"continuation_token,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ListBlobsResponse) Reset() {
	*x = ListBlobsResponse{}
	mi := &file_sidecar_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBlobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBlobsResponse) ProtoMessage() {}

func (x *ListBlobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sidecar_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBlobsResponse.ProtoReflect.Descriptor instead.
func (*ListBlobsResponse) Descriptor() ([]byte, []int) {
	return file_sidecar_proto_rawDescGZIP(), []int{8}
}

func (x *ListBlobsResponse) GetBlobs() []*BlobInfo {
	if x != nil {
		return x.Blobs
	}
	return nil
}

func (x *ListBlobsResponse) GetContinuationToken() string {
	if x != nil {
		return x.ContinuationToken
	}
	return ""
}

type BlobInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Uri              string                 `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	SizeBytes        int64                  `protobuf:"varint,2,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	ContentType      string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	LastModifiedUnix int64                  `protobuf:"varint,4,opt,name=last_modified_unix,json=lastModifiedUnix,proto3" json:"last_modified_unix,omitempty"`
	Etag             string                 `protobuf:"bytes,5,opt,name=etag,proto3" json:"etag,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BlobInfo) Reset() {
	*x = BlobInfo{}
	mi := &file_sidecar_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlobInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlobInfo) ProtoMessage() {}

func (x *BlobInfo) ProtoReflect() protoreflect.Message {
	mi := &file_sidecar_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlobInfo.ProtoReflect.Descriptor instead.
func (*BlobInfo) Descriptor() ([]byte, []int) {
	return file_sidecar_proto_rawDescGZIP(), []int{9}
}

func (x *BlobInfo) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *BlobInfo) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *BlobInfo) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *BlobInfo) GetLastModifiedUnix() int64 {
	if x != nil {
		return x.LastModifiedUnix
	}
	return 0
}

func (x *BlobInfo) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

type DeleteBlobRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Metadata       *RequestMetadata       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Provider       string                 `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	Uri            string                 `protobuf:"bytes,3,opt,name=uri,proto3" json:"uri,omitempty"`
	ProviderConfig map[string]string      `protobuf:"bytes,4,rep,name=provider_config,json=providerConfig,proto3" json:"provider_config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeleteBlobRequest) Reset() {
	*x = DeleteBlobRequest{}
	mi := &file_sidecar_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBlobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBlobRequest) ProtoMessage() {}

func (x *DeleteBlobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sidecar_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBlobRequest.ProtoReflect.Descriptor instead.
func (*DeleteBlobRequest) Descriptor() ([]byte, []int) {
	return file_sidecar_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteBlobRequest) GetMetadata() *RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *DeleteBlobRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *DeleteBlobRequest) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *DeleteBlobRequest) GetProviderConfig() map[string]string {
	if x != nil {
		return x.ProviderConfig
	}
	return nil
}

type DeleteBlobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBlobResponse) Reset() {
	*x = DeleteBlobResponse{}
	mi := &file_sidecar_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBlobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBlobResponse) ProtoMessage() {}

func (x *DeleteBlobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sidecar_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBlobResponse.ProtoReflect.Descriptor instead.
func (*DeleteBlobResponse) Descriptor() ([]byte, []int) {
	return file_sidecar_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteBlobResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteBlobResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Document processing messages
type ExtractTextRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Metadata        *RequestMetadata       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	DocumentFormat  string                 `protobuf:"bytes,2,opt,name=document_format,json=documentFormat,proto3" json:"document_format,omitempty"`
	DocumentContent []byte                 `protobuf:"bytes,3,opt,name=document_content,json=documentContent,proto3" json:"document_content,omitempty"`
	DocumentUri     string                 `protobuf:"bytes,4,opt,name=document_uri,json=documentUri,proto3" json:"document_uri,omitempty"`
	Options         map[string]string      `protobuf:"bytes,5,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ExtractTextRequest) Reset() {
	*x = ExtractTextRequest{}
	mi := &file_sidecar_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtractTextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractTextRequest) ProtoMessage() {}

func (x *ExtractTextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sidecar_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractTextRequest.ProtoReflect.Descriptor instead.
func (*ExtractTextRequest) Descriptor() ([]byte, []int) {
	return file_sidecar_proto_rawDescGZIP(), []int{12}
}

func (x *ExtractTextRequest) GetMetadata() *RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ExtractTextRequest) GetDocumentFormat() string {
	if x != nil {
		return x.DocumentFormat
	}
	return ""
}

func (x *ExtractTextRequest) GetDocumentContent() []byte {
	if x != nil {
		return x.DocumentContent
	}
	return nil
}

func (x *ExtractTextRequest) GetDocumentUri() string {
	if x != nil {
		return x.DocumentUri
	}
	return ""
}

func (x *ExtractTextRequest) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

type ExtractTextResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	PageCount     int32                  `protobuf:"varint,2,opt,name=page_count,json=pageCount,proto3" json:"page_count,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtractTextResponse) Reset() {
	*x = ExtractTextResponse{}
	mi := &file_sidecar_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtractTextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractTextResponse) ProtoMessage() {}

func (x *ExtractTextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sidecar_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractTextResponse.ProtoReflect.Descriptor instead.
func (*ExtractTextResponse) Descriptor() ([]byte, []int) {
	return file_sidecar_proto_rawDescGZIP(), []int{13}
}

func (x *ExtractTextResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ExtractTextResponse) GetPageCount() int32 {
	if x != nil {
		return x.PageCount
	}
	return 0
}

func (x *ExtractTextResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ProcessDocumentRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Metadata        *RequestMetadata       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Operation       string                 `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"`
	InputFormat     string                 `protobuf:"bytes,3,opt,name=input_format,json=inputFormat,proto3" json:"input_format,omitempty"`
	OutputFormat    string                 `protobuf:"bytes,4,opt,name=output_format,json=outputFormat,proto3" json:"output_format,omitempty"`
	InputContent    []byte                 `protobuf:"bytes,5,opt,name=input_content,json=inputContent,proto3" json:"input_content,omitempty"`
	InputUri        string                 `protobuf:"bytes,6,opt,name=input_uri,json=inputUri,proto3" json:"input_uri,omitempty"`
	OperationParams map[string]string      `protobuf:"bytes,7,rep,name=operation_params,json=operationParams,proto3" json:"operation_params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ProcessDocumentRequest) Reset() {
	*x = ProcessDocumentRequest{}
	mi := &file_sidecar_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessDocumentRequest) ProtoMessage() {}

func (x *ProcessDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sidecar_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessDocumentRequest.ProtoReflect.Descriptor instead.
func (*ProcessDocumentRequest) Descriptor() ([]byte, []int) {
	return file_sidecar_proto_rawDescGZIP(), []int{14}
}

func (x *ProcessDocumentRequest) GetMetadata() *RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ProcessDocumentRequest) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *ProcessDocumentRequest) GetInputFormat() string {
	if x != nil {
		return x.InputFormat
	}
	return ""
}

func (x *ProcessDocumentRequest) GetOutputFormat() string {
	if x != nil {
		return x.OutputFormat
	}
	return ""
}

func (x *ProcessDocumentRequest) GetInputContent() []byte {
	if x != nil {
		return x.InputContent
	}
	return nil
}

func (x *ProcessDocumentRequest) GetInputUri() string {
	if x != nil {
		return x.InputUri
	}
	return ""
}

func (x *ProcessDocumentRequest) GetOperationParams() map[string]string {
	if x != nil {
		return x.OperationParams
	}
	return nil
}

type ProcessDocumentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OutputUri     string                 `protobuf:"bytes,1,opt,name=output_uri,json=outputUri,proto3" json:"output_uri,omitempty"`
	OutputContent []byte                 `protobuf:"bytes,2,opt,name=output_content,json=outputContent,proto3" json:"output_content,omitempty"`
	OutputFormat  string                 `protobuf:"bytes,3,opt,name=output_format,json=outputFormat,proto3" json:"output_format,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessDocumentResponse) Reset() {
	*x = ProcessDocumentResponse{}
	mi := &file_sidecar_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessDocumentResponse) ProtoMessage() {}

func (x *ProcessDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sidecar_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessDocumentResponse.ProtoReflect.Descriptor instead.
func (*ProcessDocumentResponse) Descriptor() ([]byte, []int) {
	return file_sidecar_proto_rawDescGZIP(), []int{15}
}

func (x *ProcessDocumentResponse) GetOutputUri() string {
	if x != nil {
		return x.OutputUri
	}
	return ""
}

func (x *ProcessDocumentResponse) GetOutputContent() []byte {
	if x != nil {
		return x.OutputContent
	}
	return nil
}

func (x *ProcessDocumentResponse) GetOutputFormat() string {
	if x != nil {
		return x.OutputFormat
	}
	return ""
}

func (x *ProcessDocumentResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_sidecar_proto protoreflect.FileDescriptor

const file_sidecar_proto_rawDesc = "" +
	"\n" +
	"\rsidecar.proto\x12\x14armorclaw.sidecar.v1\"\xb1\x01\n" +
	"\x0fRequestMetadata\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12'\n" +
	"\x0fephemeral_token\x18\x02 \x01(\tR\x0eephemeralToken\x12%\n" +
	"\x0etimestamp_unix\x18\x03 \x01(\x03R\rtimestampUnix\x12/\n" +
	"\x13operation_signature\x18\x04 \x01(\tR\x12operationSignature\"\x14\n" +
	"\x12HealthCheckRequest\"\xc3\x01\n" +
	"\x13HealthCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12%\n" +
	"\x0euptime_seconds\x18\x02 \x01(\x03R\ruptimeSeconds\x12'\n" +
	"\x0factive_requests\x18\x03 \x01(\x05R\x0eactiveRequests\x12*\n" +
	"\x11memory_used_bytes\x18\x04 \x01(\x03R\x0fmemoryUsedBytes\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\"\xa9\x03\n" +
	"\x11UploadBlobRequest\x12A\n" +
	"\bmetadata\x18\x01 \x01(\v2%.armorclaw.sidecar.v1.RequestMetadataR\bmetadata\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\x12'\n" +
	"\x0fdestination_uri\x18\x03 \x01(\tR\x0edestinationUri\x12!\n" +
	"\fcontent_type\x18\x04 \x01(\tR\vcontentType\x12d\n" +
	"\x0fprovider_config\x18\x05 \x03(\v2;.armorclaw.sidecar.v1.UploadBlobRequest.ProviderConfigEntryR\x0eproviderConfig\x12\x18\n" +
	"\acontent\x18\x06 \x01(\fR\acontent\x12&\n" +
	"\x0flocal_file_path\x18\a \x01(\tR\rlocalFilePath\x1aA\n" +
	"\x13ProviderConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb7\x01\n" +
	"\x12UploadBlobResponse\x12\x17\n" +
	"\ablob_id\x18\x01 \x01(\tR\x06blobId\x12\x12\n" +
	"\x04etag\x18\x02 \x01(\tR\x04etag\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x03R\tsizeBytes\x12.\n" +
	"\x13content_hash_sha256\x18\x04 \x01(\tR\x11contentHashSha256\x12%\n" +
	"\x0etimestamp_unix\x18\x05 \x01(\x03R\rtimestampUnix\"\xfe\x02\n" +
	"\x13DownloadBlobRequest\x12A\n" +
	"\bmetadata\x18\x01 \x01(\v2%.armorclaw.sidecar.v1.RequestMetadataR\bmetadata\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\x12\x1d\n" +
	"\n" +
	"source_uri\x18\x03 \x01(\tR\tsourceUri\x12f\n" +
	"\x0fprovider_config\x18\x04 \x03(\v2=.armorclaw.sidecar.v1.DownloadBlobRequest.ProviderConfigEntryR\x0eproviderConfig\x12!\n" +
	"\foffset_bytes\x18\x05 \x01(\x03R\voffsetBytes\x12\x1b\n" +
	"\tmax_bytes\x18\x06 \x01(\x03R\bmaxBytes\x1aA\n" +
	"\x13ProviderConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"P\n" +
	"\tBlobChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x12\x17\n" +
	"\ais_last\x18\x03 \x01(\bR\x06isLast\"\xd2\x02\n" +
	"\x10ListBlobsRequest\x12A\n" +
	"\bmetadata\x18\x01 \x01(\v2%.armorclaw.sidecar.v1.RequestMetadataR\bmetadata\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\x12\x16\n" +
	"\x06prefix\x18\x03 \x01(\tR\x06prefix\x12\x1f\n" +
	"\vmax_results\x18\x04 \x01(\x05R\n" +
	"maxResults\x12c\n" +
	"\x0fprovider_config\x18\x05 \x03(\v2:.armorclaw.sidecar.v1.ListBlobsRequest.ProviderConfigEntryR\x0eproviderConfig\x1aA\n" +
	"\x13ProviderConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"x\n" +
	"\x11ListBlobsResponse\x124\n" +
	"\x05blobs\x18\x01 \x03(\v2\x1e.armorclaw.sidecar.v1.BlobInfoR\x05blobs\x12-\n" +
	"\x12continuation_token\x18\x02 \x01(\tR\x11continuationToken\"\xa0\x01\n" +
	"\bBlobInfo\x12\x10\n" +
	"\x03uri\x18\x01 \x01(\tR\x03uri\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x02 \x01(\x03R\tsizeBytes\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\x12,\n" +
	"\x12last_modified_unix\x18\x04 \x01(\x03R\x10lastModifiedUnix\x12\x12\n" +
	"\x04etag\x18\x05 \x01(\tR\x04etag\"\xad\x02\n" +
	"\x11DeleteBlobRequest\x12A\n" +
	"\bmetadata\x18\x01 \x01(\v2%.armorclaw.sidecar.v1.RequestMetadataR\bmetadata\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\x12\x10\n" +
	"\x03uri\x18\x03 \x01(\tR\x03uri\x12d\n" +
	"\x0fprovider_config\x18\x04 \x03(\v2;.armorclaw.sidecar.v1.DeleteBlobRequest.ProviderConfigEntryR\x0eproviderConfig\x1aA\n" +
	"\x13ProviderConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"H\n" +
	"\x12DeleteBlobResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xdb\x02\n" +
	"\x12ExtractTextRequest\x12A\n" +
	"\bmetadata\x18\x01 \x01(\v2%.armorclaw.sidecar.v1.RequestMetadataR\bmetadata\x12'\n" +
	"\x0fdocument_format\x18\x02 \x01(\tR\x0edocumentFormat\x12)\n" +
	"\x10document_content\x18\x03 \x01(\fR\x0fdocumentContent\x12!\n" +
	"\fdocument_uri\x18\x04 \x01(\tR\vdocumentUri\x12O\n" +
	"\aoptions\x18\x05 \x03(\v25.armorclaw.sidecar.v1.ExtractTextRequest.OptionsEntryR\aoptions\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xda\x01\n" +
	"\x13ExtractTextResponse\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x1d\n" +
	"\n" +
	"page_count\x18\x02 \x01(\x05R\tpageCount\x12S\n" +
	"\bmetadata\x18\x03 \x03(\v27.armorclaw.sidecar.v1.ExtractTextResponse.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb5\x03\n" +
	"\x16ProcessDocumentRequest\x12A\n" +
	"\bmetadata\x18\x01 \x01(\v2%.armorclaw.sidecar.v1.RequestMetadataR\bmetadata\x12\x1c\n" +
	"\toperation\x18\x02 \x01(\tR\toperation\x12!\n" +
	"\finput_format\x18\x03 \x01(\tR\vinputFormat\x12#\n" +
	"\routput_format\x18\x04 \x01(\tR\foutputFormat\x12#\n" +
	"\rinput_content\x18\x05 \x01(\fR\finputContent\x12\x1b\n" +
	"\tinput_uri\x18\x06 \x01(\tR\binputUri\x12l\n" +
	"\x10operation_params\x18\a \x03(\v2A.armorclaw.sidecar.v1.ProcessDocumentRequest.OperationParamsEntryR\x0foperationParams\x1aB\n" +
	"\x14OperationParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9a\x02\n" +
	"\x17ProcessDocumentResponse\x12\x1d\n" +
	"\n" +
	"output_uri\x18\x01 \x01(\tR\toutputUri\x12%\n" +
	"\x0eoutput_content\x18\x02 \x01(\fR\routputContent\x12#\n" +
	"\routput_format\x18\x03 \x01(\tR\foutputFormat\x12W\n" +
	"\bmetadata\x18\x04 \x03(\v2;.armorclaw.sidecar.v1.ProcessDocumentResponse.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xc6\x05\n" +
	"\x0eSidecarService\x12b\n" +
	"\vHealthCheck\x12(.armorclaw.sidecar.v1.HealthCheckRequest\x1a).armorclaw.sidecar.v1.HealthCheckResponse\x12_\n" +
	"\n" +
	"UploadBlob\x12'.armorclaw.sidecar.v1.UploadBlobRequest\x1a(.armorclaw.sidecar.v1.UploadBlobResponse\x12\\\n" +
	"\fDownloadBlob\x12).armorclaw.sidecar.v1.DownloadBlobRequest\x1a\x1f.armorclaw.sidecar.v1.BlobChunk0\x01\x12\\\n" +
	"\tListBlobs\x12&.armorclaw.sidecar.v1.ListBlobsRequest\x1a'.armorclaw.sidecar.v1.ListBlobsResponse\x12_\n" +
	"\n" +
	"DeleteBlob\x12'.armorclaw.sidecar.v1.DeleteBlobRequest\x1a(.armorclaw.sidecar.v1.DeleteBlobResponse\x12b\n" +
	"\vExtractText\x12(.armorclaw.sidecar.v1.ExtractTextRequest\x1a).armorclaw.sidecar.v1.ExtractTextResponse\x12n\n" +
	"\x0fProcessDocument\x12,.armorclaw.sidecar.v1.ProcessDocumentRequest\x1a-.armorclaw.sidecar.v1.ProcessDocumentResponseB,Z*github.com/armorclaw/sidecar/proto;sidecarb\x06proto3"

var (
	file_sidecar_proto_rawDescOnce sync.Once
	file_sidecar_proto_rawDescData []byte
)

func file_sidecar_proto_rawDescGZIP() []byte {
	file_sidecar_proto_rawDescOnce.Do(func() {
		file_sidecar_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sidecar_proto_rawDesc), len(file_sidecar_proto_rawDesc)))
	})
	return file_sidecar_proto_rawDescData
}

var file_sidecar_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_sidecar_proto_goTypes = []any{
	(*RequestMetadata)(nil),         // 0: armorclaw.sidecar.v1.RequestMetadata
	(*HealthCheckRequest)(nil),      // 1: armorclaw.sidecar.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil),     // 2: armorclaw.sidecar.v1.HealthCheckResponse
	(*UploadBlobRequest)(nil),       // 3: armorclaw.sidecar.v1.UploadBlobRequest
	(*UploadBlobResponse)(nil),      // 4: armorclaw.sidecar.v1.UploadBlobResponse
	(*DownloadBlobRequest)(nil),     // 5: armorclaw.sidecar.v1.DownloadBlobRequest
	(*BlobChunk)(nil),               // 6: armorclaw.sidecar.v1.BlobChunk
	(*ListBlobsRequest)(nil),        // 7: armorclaw.sidecar.v1.ListBlobsRequest
	(*ListBlobsResponse)(nil),       // 8: armorclaw.sidecar.v1.ListBlobsResponse
	(*BlobInfo)(nil),                // 9: armorclaw.sidecar.v1.BlobInfo
	(*DeleteBlobRequest)(nil),       // 10: armorclaw.sidecar.v1.DeleteBlobRequest
	(*DeleteBlobResponse)(nil),      // 11: armorclaw.sidecar.v1.DeleteBlobResponse
	(*ExtractTextRequest)(nil),      // 12: armorclaw.sidecar.v1.ExtractTextRequest
	(*ExtractTextResponse)(nil),     // 13: armorclaw.sidecar.v1.ExtractTextResponse
	(*ProcessDocumentRequest)(nil),  // 14: armorclaw.sidecar.v1.ProcessDocumentRequest
	(*ProcessDocumentResponse)(nil), // 15: armorclaw.sidecar.v1.ProcessDocumentResponse
	nil,                             // 16: armorclaw.sidecar.v1.UploadBlobRequest.ProviderConfigEntry
	nil,                             // 17: armorclaw.sidecar.v1.DownloadBlobRequest.ProviderConfigEntry
	nil,                             // 18: armorclaw.sidecar.v1.ListBlobsRequest.ProviderConfigEntry
	nil,                             // 19: armorclaw.sidecar.v1.DeleteBlobRequest.ProviderConfigEntry
	nil,                             // 20: armorclaw.sidecar.v1.ExtractTextRequest.OptionsEntry
	nil,                             // 21: armorclaw.sidecar.v1.ExtractTextResponse.MetadataEntry
	nil,                             // 22: armorclaw.sidecar.v1.ProcessDocumentRequest.OperationParamsEntry
	nil,                             // 23: armorclaw.sidecar.v1.ProcessDocumentResponse.MetadataEntry
}
var file_sidecar_proto_depIdxs = []int32{
	0,  // 0: armorclaw.sidecar.v1.UploadBlobRequest.metadata:type_name -> armorclaw.sidecar.v1.RequestMetadata
	16, // 1: armorclaw.sidecar.v1.UploadBlobRequest.provider_config:type_name -> armorclaw.sidecar.v1.UploadBlobRequest.ProviderConfigEntry
	0,  // 2: armorclaw.sidecar.v1.DownloadBlobRequest.metadata:type_name -> armorclaw.sidecar.v1.RequestMetadata
	17, // 3: armorclaw.sidecar.v1.DownloadBlobRequest.provider_config:type_name -> armorclaw.sidecar.v1.DownloadBlobRequest.ProviderConfigEntry
	0,  // 4: armorclaw.sidecar.v1.ListBlobsRequest.metadata:type_name -> armorclaw.sidecar.v1.RequestMetadata
	18, // 5: armorclaw.sidecar.v1.ListBlobsRequest.provider_config:type_name -> armorclaw.sidecar.v1.ListBlobsRequest.ProviderConfigEntry
	9,  // 6: armorclaw.sidecar.v1.ListBlobsResponse.blobs:type_name -> armorclaw.sidecar.v1.BlobInfo
	0,  // 7: armorclaw.sidecar.v1.DeleteBlobRequest.metadata:type_name -> armorclaw.sidecar.v1.RequestMetadata
	19, // 8: armorclaw.sidecar.v1.DeleteBlobRequest.provider_config:type_name -> armorclaw.sidecar.v1.DeleteBlobRequest.ProviderConfigEntry
	0,  // 9: armorclaw.sidecar.v1.ExtractTextRequest.metadata:type_name -> armorclaw.sidecar.v1.RequestMetadata
	20, // 10: armorclaw.sidecar.v1.ExtractTextRequest.options:type_name -> armorclaw.sidecar.v1.ExtractTextRequest.OptionsEntry
	21, // 11: armorclaw.sidecar.v1.ExtractTextResponse.metadata:type_name -> armorclaw.sidecar.v1.ExtractTextResponse.MetadataEntry
	0,  // 12: armorclaw.sidecar.v1.ProcessDocumentRequest.metadata:type_name -> armorclaw.sidecar.v1.RequestMetadata
	22, // 13: armorclaw.sidecar.v1.ProcessDocumentRequest.operation_params:type_name -> armorclaw.sidecar.v1.ProcessDocumentRequest.OperationParamsEntry
	23, // 14: armorclaw.sidecar.v1.ProcessDocumentResponse.metadata:type_name -> armorclaw.sidecar.v1.ProcessDocumentResponse.MetadataEntry
	1,  // 15: armorclaw.sidecar.v1.SidecarService.HealthCheck:input_type -> armorclaw.sidecar.v1.HealthCheckRequest
	3,  // 16: armorclaw.sidecar.v1.SidecarService.UploadBlob:input_type -> armorclaw.sidecar.v1.UploadBlobRequest
	5,  // 17: armorclaw.sidecar.v1.SidecarService.DownloadBlob:input_type -> armorclaw.sidecar.v1.DownloadBlobRequest
	7,  // 18: armorclaw.sidecar.v1.SidecarService.ListBlobs:input_type -> armorclaw.sidecar.v1.ListBlobsRequest
	10, // 19: armorclaw.sidecar.v1.SidecarService.DeleteBlob:input_type -> armorclaw.sidecar.v1.DeleteBlobRequest
	12, // 20: armorclaw.sidecar.v1.SidecarService.ExtractText:input_type -> armorclaw.sidecar.v1.ExtractTextRequest
	14, // 21: armorclaw.sidecar.v1.SidecarService.ProcessDocument:input_type -> armorclaw.sidecar.v1.ProcessDocumentRequest
	2,  // 22: armorclaw.sidecar.v1.SidecarService.HealthCheck:output_type -> armorclaw.sidecar.v1.HealthCheckResponse
	4,  // 23: armorclaw.sidecar.v1.SidecarService.UploadBlob:output_type -> armorclaw.sidecar.v1.UploadBlobResponse
	6,  // 24: armorclaw.sidecar.v1.SidecarService.DownloadBlob:output_type -> armorclaw.sidecar.v1.BlobChunk
	8,  // 25: armorclaw.sidecar.v1.SidecarService.ListBlobs:output_type -> armorclaw.sidecar.v1.ListBlobsResponse
	11, // 26: armorclaw.sidecar.v1.SidecarService.DeleteBlob:output_type -> armorclaw.sidecar.v1.DeleteBlobResponse
	13, // 27: armorclaw.sidecar.v1.SidecarService.ExtractText:output_type -> armorclaw.sidecar.v1.ExtractTextResponse
	15, // 28: armorclaw.sidecar.v1.SidecarService.ProcessDocument:output_type -> armorclaw.sidecar.v1.ProcessDocumentResponse
	22, // [22:29] is the sub-list for method output_type
	15, // [15:22] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_sidecar_proto_init() }
func file_sidecar_proto_init() {
	if File_sidecar_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sidecar_proto_rawDesc), len(file_sidecar_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sidecar_proto_goTypes,
		DependencyIndexes: file_sidecar_proto_depIdxs,
		MessageInfos:      file_sidecar_proto_msgTypes,
	}.Build()
	File_sidecar_proto = out.File
	file_sidecar_proto_goTypes = nil
	file_sidecar_proto_depIdxs = nil
}
