# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import sidecar_pb2 as sidecar__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in sidecar_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SidecarServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.HealthCheck = channel.unary_unary(
                '/armorclaw.sidecar.v1.SidecarService/HealthCheck',
                request_serializer=sidecar__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=sidecar__pb2.HealthCheckResponse.FromString,
                _registered_method=True)
        self.UploadBlob = channel.unary_unary(
                '/armorclaw.sidecar.v1.SidecarService/UploadBlob',
                request_serializer=sidecar__pb2.UploadBlobRequest.SerializeToString,
                response_deserializer=sidecar__pb2.UploadBlobResponse.FromString,
                _registered_method=True)
        self.DownloadBlob = channel.unary_stream(
                '/armorclaw.sidecar.v1.SidecarService/DownloadBlob',
                request_serializer=sidecar__pb2.DownloadBlobRequest.SerializeToString,
                response_deserializer=sidecar__pb2.BlobChunk.FromString,
                _registered_method=True)
        self.ListBlobs = channel.unary_unary(
                '/armorclaw.sidecar.v1.SidecarService/ListBlobs',
                request_serializer=sidecar__pb2.ListBlobsRequest.SerializeToString,
                response_deserializer=sidecar__pb2.ListBlobsResponse.FromString,
                _registered_method=True)
        self.DeleteBlob = channel.unary_unary(
                '/armorclaw.sidecar.v1.SidecarService/DeleteBlob',
                request_serializer=sidecar__pb2.DeleteBlobRequest.SerializeToString,
                response_deserializer=sidecar__pb2.DeleteBlobResponse.FromString,
                _registered_method=True)
        self.ExtractText = channel.unary_unary(
                '/armorclaw.sidecar.v1.SidecarService/ExtractText',
                request_serializer=sidecar__pb2.ExtractTextRequest.SerializeToString,
                response_deserializer=sidecar__pb2.ExtractTextResponse.FromString,
                _registered_method=True)
        self.ProcessDocument = channel.unary_unary(
                '/armorclaw.sidecar.v1.SidecarService/ProcessDocument',
                request_serializer=sidecar__pb2.ProcessDocumentRequest.SerializeToString,
                response_deserializer=sidecar__pb2.ProcessDocumentResponse.FromString,
                _registered_method=True)


class SidecarServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def HealthCheck(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadBlob(self, request, context):
        """Storage operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadBlob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListBlobs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteBlob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExtractText(self, request, context):
        """Document operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProcessDocument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SidecarServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=sidecar__pb2.HealthCheckRequest.FromString,
                    response_serializer=sidecar__pb2.HealthCheckResponse.SerializeToString,
            ),
            'UploadBlob': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadBlob,
                    request_deserializer=sidecar__pb2.UploadBlobRequest.FromString,
                    response_serializer=sidecar__pb2.UploadBlobResponse.SerializeToString,
            ),
            'DownloadBlob': grpc.unary_stream_rpc_method_handler(
                    servicer.DownloadBlob,
                    request_deserializer=sidecar__pb2.DownloadBlobRequest.FromString,
                    response_serializer=sidecar__pb2.BlobChunk.SerializeToString,
            ),
            'ListBlobs': grpc.unary_unary_rpc_method_handler(
                    servicer.ListBlobs,
                    request_deserializer=sidecar__pb2.ListBlobsRequest.FromString,
                    response_serializer=sidecar__pb2.ListBlobsResponse.SerializeToString,
            ),
            'DeleteBlob': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteBlob,
                    request_deserializer=sidecar__pb2.DeleteBlobRequest.FromString,
                    response_serializer=sidecar__pb2.DeleteBlobResponse.SerializeToString,
            ),
            'ExtractText': grpc.unary_unary_rpc_method_handler(
                    servicer.ExtractText,
                    request_deserializer=sidecar__pb2.ExtractTextRequest.FromString,
                    response_serializer=sidecar__pb2.ExtractTextResponse.SerializeToString,
            ),
            'ProcessDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessDocument,
                    request_deserializer=sidecar__pb2.ProcessDocumentRequest.FromString,
                    response_serializer=sidecar__pb2.ProcessDocumentResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'armorclaw.sidecar.v1.SidecarService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('armorclaw.sidecar.v1.SidecarService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SidecarService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/armorclaw.sidecar.v1.SidecarService/HealthCheck',
            sidecar__pb2.HealthCheckRequest.SerializeToString,
            sidecar__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadBlob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/armorclaw.sidecar.v1.SidecarService/UploadBlob',
            sidecar__pb2.UploadBlobRequest.SerializeToString,
            sidecar__pb2.UploadBlobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DownloadBlob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/armorclaw.sidecar.v1.SidecarService/DownloadBlob',
            sidecar__pb2.DownloadBlobRequest.SerializeToString,
            sidecar__pb2.BlobChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListBlobs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/armorclaw.sidecar.v1.SidecarService/ListBlobs',
            sidecar__pb2.ListBlobsRequest.SerializeToString,
            sidecar__pb2.ListBlobsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteBlob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/armorclaw.sidecar.v1.SidecarService/DeleteBlob',
            sidecar__pb2.DeleteBlobRequest.SerializeToString,
            sidecar__pb2.DeleteBlobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExtractText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/armorclaw.sidecar.v1.SidecarService/ExtractText',
            sidecar__pb2.ExtractTextRequest.SerializeToString,
            sidecar__pb2.ExtractTextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProcessDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/armorclaw.sidecar.v1.SidecarService/ProcessDocument',
            sidecar__pb2.ProcessDocumentRequest.SerializeToString,
            sidecar__pb2.ProcessDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
