package com.armorclaw.shared.domain.model

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

/**
 * Unseal Challenge
 *
 * Challenge generated by the Bridge for keystore unsealing.
 * The client must derive a key from the password and wrap it
 * with the server's public key.
 */
@Serializable
data class UnsealChallenge(
    @SerialName("challenge_id")
    val challengeId: String,

    @SerialName("nonce")
    val nonce: String, // Base64-encoded nonce for key derivation

    @SerialName("server_public_key")
    val serverPublicKey: String, // PEM-encoded RSA public key

    @SerialName("expires_at")
    val expiresAt: Long,

    @SerialName("key_derivation")
    val keyDerivation: KeyDerivationParams? = null
)

/**
 * Key Derivation Parameters
 *
 * Parameters for deriving the KEK from password.
 */
@Serializable
data class KeyDerivationParams(
    @SerialName("algorithm")
    val algorithm: String, // "argon2id" or "pbkdf2"

    @SerialName("iterations")
    val iterations: Int? = null, // For PBKDF2

    @SerialName("memory_kb")
    val memoryKb: Int? = null, // For Argon2

    @SerialName("parallelism")
    val parallelism: Int? = null, // For Argon2

    @SerialName("salt")
    val salt: String? = null // Base64-encoded salt (if server provides)
)

/**
 * Unseal Request
 *
 * Request to unseal the keystore with a wrapped key.
 */
@Serializable
data class UnsealRequest(
    @SerialName("challenge_id")
    val challengeId: String,

    @SerialName("wrapped_key")
    val wrappedKey: String, // Base64-encoded, RSA-OAEP wrapped KEK

    @SerialName("client_public_key")
    val clientPublicKey: String? = null, // For response encryption
    @SerialName("unseal_method")
    val unsealMethod: String = "password" // "password" or "biometric"
)

/**
 * Unseal Result
 *
 * Result of an unseal attempt.
 */
@Serializable
data class UnsealResult(
    @SerialName("success")
    val success: Boolean,

    @SerialName("error")
    val error: String? = null,

    @SerialName("error_code")
    val errorCode: String? = null, // "invalid_password", "challenge_expired", "keystore_error"

    @SerialName("session_expires_at")
    val sessionExpiresAt: Long? = null,

    @SerialName("session_duration_seconds")
    val sessionDurationSeconds: Long? = null
)

/**
 * Session Extension Result
 *
 * Result of extending an unsealed session.
 */
@Serializable
data class SessionExtensionResult(
    @SerialName("success")
    val success: Boolean,

    @SerialName("new_expires_at")
    val newExpiresAt: Long? = null,

    @SerialName("error")
    val error: String? = null,

    @SerialName("max_extensions_reached")
    val maxExtensionsReached: Boolean = false
)

/**
 * Keystore Status Response
 *
 * Response from keystore.sealed RPC method.
 */
@Serializable
data class KeystoreStatusResponse(
    @SerialName("sealed")
    val sealed: Boolean,

    @SerialName("seal_state")
    val sealState: String, // "sealed", "unsealed", "error"

    @SerialName("remaining_seconds")
    val remainingSeconds: Long? = null,

    @SerialName("session_extensions_used")
    val sessionExtensionsUsed: Int? = null,

    @SerialName("max_extensions")
    val maxExtensions: Int? = null,

    @SerialName("last_unsealed_at")
    val lastUnsealedAt: Long? = null,

    @SerialName("last_unsealed_by")
    val lastUnsealedBy: String? = null,

    @SerialName("error_message")
    val errorMessage: String? = null
) {
    /**
     * Convert to domain KeystoreStatus
     */
    fun toKeystoreStatus(): KeystoreStatus {
        return when {
            !sealed -> KeystoreStatus.Unsealed(
                expiresAt = System.currentTimeMillis() + (remainingSeconds ?: 0) * 1000,
                unsealedBy = lastUnsealedBy?.let {
                    if (it == "biometric") UnsealMethod.BIOMETRIC else UnsealMethod.PASSWORD
                } ?: UnsealMethod.PASSWORD
            )
            sealState == "error" -> KeystoreStatus.Error(errorMessage ?: "Unknown error")
            else -> KeystoreStatus.Sealed()
        }
    }
}
