// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.3
// source: governance.proto

package governance

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Governance_IssueEphemeralToken_FullMethodName   = "/vault.governance.v1.Governance/IssueEphemeralToken"
	Governance_ConsumeEphemeralToken_FullMethodName = "/vault.governance.v1.Governance/ConsumeEphemeralToken"
	Governance_ZeroizeToolSecrets_FullMethodName    = "/vault.governance.v1.Governance/ZeroizeToolSecrets"
	Governance_SubscribeEvents_FullMethodName       = "/vault.governance.v1.Governance/SubscribeEvents"
)

// GovernanceClient is the client API for Governance service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Governance provides the gRPC control plane for ephemeral token lifecycle
// and vault event streaming.
//
// This service manages short-lived tokens that grant scoped access to secrets
// without exposing plaintext values to callers. Tokens are consumed exactly
// once and automatically expire after their TTL.
//
// Token lifecycle:
//  1. IssueEphemeralToken — vault stores plaintext, returns token_id
//  2. ConsumeEphemeralToken — caller redeems token_id, receives plaintext
//  3. Token is destroyed after successful consumption or TTL expiry
//
// Security:
//   - Tokens are single-use (consumed on first redeem)
//   - All tokens have a bounded TTL (ttl_ms)
//   - ZeroizeToolSecrets provides emergency cleanup capability
//   - All operations are auditable via SubscribeEvents
type GovernanceClient interface {
	// Issue an ephemeral token that wraps a plaintext secret.
	//
	// The vault stores the plaintext in memory (never persisted to disk)
	// and returns a token_id that can be redeemed exactly once within the
	// specified TTL window.
	//
	// Errors:
	//   - INVALID_ARGUMENT: Missing required fields (token_id, plaintext)
	//   - RESOURCE_EXHAUSTED: Too many active tokens for this session
	//   - INTERNAL: Vault memory allocation failure
	IssueEphemeralToken(ctx context.Context, in *IssueTokenRequest, opts ...grpc.CallOption) (*IssueTokenResponse, error)
	// Consume (redeem) an ephemeral token to retrieve the plaintext secret.
	//
	// The token is destroyed after successful consumption. A second
	// consumption attempt for the same token_id will fail.
	//
	// Errors:
	//   - NOT_FOUND: token_id does not exist or was already consumed
	//   - DEADLINE_EXCEEDED: Token TTL has expired
	//   - PERMISSION_DENIED: session_id does not match the issuing session
	//   - INVALID_ARGUMENT: Missing required fields (token_id, session_id)
	ConsumeEphemeralToken(ctx context.Context, in *ConsumeTokenRequest, opts ...grpc.CallOption) (*ConsumeTokenResponse, error)
	// Zeroize (securely erase) all secrets held for a given tool/session.
	//
	// This is an emergency cleanup operation. All in-memory secrets
	// associated with the tool_name and session_id are overwritten with
	// zeros and then freed. The operation is irreversible.
	//
	// Errors:
	//   - NOT_FOUND: No secrets found for the given tool_name + session_id
	//   - INVALID_ARGUMENT: Missing required fields (tool_name, session_id)
	ZeroizeToolSecrets(ctx context.Context, in *ZeroizeRequest, opts ...grpc.CallOption) (*ZeroizeResponse, error)
	// Subscribe to a stream of vault events.
	//
	// Returns a server-streaming response of VaultEventStream messages.
	// Events include token issuance, consumption, expiry, and zeroization.
	// The optional session_id field filters events to a specific session.
	//
	// Errors:
	//   - INVALID_ARGUMENT: Malformed subscription request
	//   - UNAVAILABLE: Vault event subsystem is not initialized
	SubscribeEvents(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[VaultEventStream], error)
}

type governanceClient struct {
	cc grpc.ClientConnInterface
}

func NewGovernanceClient(cc grpc.ClientConnInterface) GovernanceClient {
	return &governanceClient{cc}
}

func (c *governanceClient) IssueEphemeralToken(ctx context.Context, in *IssueTokenRequest, opts ...grpc.CallOption) (*IssueTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IssueTokenResponse)
	err := c.cc.Invoke(ctx, Governance_IssueEphemeralToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *governanceClient) ConsumeEphemeralToken(ctx context.Context, in *ConsumeTokenRequest, opts ...grpc.CallOption) (*ConsumeTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConsumeTokenResponse)
	err := c.cc.Invoke(ctx, Governance_ConsumeEphemeralToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *governanceClient) ZeroizeToolSecrets(ctx context.Context, in *ZeroizeRequest, opts ...grpc.CallOption) (*ZeroizeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ZeroizeResponse)
	err := c.cc.Invoke(ctx, Governance_ZeroizeToolSecrets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *governanceClient) SubscribeEvents(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[VaultEventStream], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Governance_ServiceDesc.Streams[0], Governance_SubscribeEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, VaultEventStream]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Governance_SubscribeEventsClient = grpc.ServerStreamingClient[VaultEventStream]

// GovernanceServer is the server API for Governance service.
// All implementations must embed UnimplementedGovernanceServer
// for forward compatibility.
//
// Governance provides the gRPC control plane for ephemeral token lifecycle
// and vault event streaming.
//
// This service manages short-lived tokens that grant scoped access to secrets
// without exposing plaintext values to callers. Tokens are consumed exactly
// once and automatically expire after their TTL.
//
// Token lifecycle:
//  1. IssueEphemeralToken — vault stores plaintext, returns token_id
//  2. ConsumeEphemeralToken — caller redeems token_id, receives plaintext
//  3. Token is destroyed after successful consumption or TTL expiry
//
// Security:
//   - Tokens are single-use (consumed on first redeem)
//   - All tokens have a bounded TTL (ttl_ms)
//   - ZeroizeToolSecrets provides emergency cleanup capability
//   - All operations are auditable via SubscribeEvents
type GovernanceServer interface {
	// Issue an ephemeral token that wraps a plaintext secret.
	//
	// The vault stores the plaintext in memory (never persisted to disk)
	// and returns a token_id that can be redeemed exactly once within the
	// specified TTL window.
	//
	// Errors:
	//   - INVALID_ARGUMENT: Missing required fields (token_id, plaintext)
	//   - RESOURCE_EXHAUSTED: Too many active tokens for this session
	//   - INTERNAL: Vault memory allocation failure
	IssueEphemeralToken(context.Context, *IssueTokenRequest) (*IssueTokenResponse, error)
	// Consume (redeem) an ephemeral token to retrieve the plaintext secret.
	//
	// The token is destroyed after successful consumption. A second
	// consumption attempt for the same token_id will fail.
	//
	// Errors:
	//   - NOT_FOUND: token_id does not exist or was already consumed
	//   - DEADLINE_EXCEEDED: Token TTL has expired
	//   - PERMISSION_DENIED: session_id does not match the issuing session
	//   - INVALID_ARGUMENT: Missing required fields (token_id, session_id)
	ConsumeEphemeralToken(context.Context, *ConsumeTokenRequest) (*ConsumeTokenResponse, error)
	// Zeroize (securely erase) all secrets held for a given tool/session.
	//
	// This is an emergency cleanup operation. All in-memory secrets
	// associated with the tool_name and session_id are overwritten with
	// zeros and then freed. The operation is irreversible.
	//
	// Errors:
	//   - NOT_FOUND: No secrets found for the given tool_name + session_id
	//   - INVALID_ARGUMENT: Missing required fields (tool_name, session_id)
	ZeroizeToolSecrets(context.Context, *ZeroizeRequest) (*ZeroizeResponse, error)
	// Subscribe to a stream of vault events.
	//
	// Returns a server-streaming response of VaultEventStream messages.
	// Events include token issuance, consumption, expiry, and zeroization.
	// The optional session_id field filters events to a specific session.
	//
	// Errors:
	//   - INVALID_ARGUMENT: Malformed subscription request
	//   - UNAVAILABLE: Vault event subsystem is not initialized
	SubscribeEvents(*SubscribeRequest, grpc.ServerStreamingServer[VaultEventStream]) error
	mustEmbedUnimplementedGovernanceServer()
}

// UnimplementedGovernanceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGovernanceServer struct{}

func (UnimplementedGovernanceServer) IssueEphemeralToken(context.Context, *IssueTokenRequest) (*IssueTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IssueEphemeralToken not implemented")
}
func (UnimplementedGovernanceServer) ConsumeEphemeralToken(context.Context, *ConsumeTokenRequest) (*ConsumeTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConsumeEphemeralToken not implemented")
}
func (UnimplementedGovernanceServer) ZeroizeToolSecrets(context.Context, *ZeroizeRequest) (*ZeroizeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ZeroizeToolSecrets not implemented")
}
func (UnimplementedGovernanceServer) SubscribeEvents(*SubscribeRequest, grpc.ServerStreamingServer[VaultEventStream]) error {
	return status.Error(codes.Unimplemented, "method SubscribeEvents not implemented")
}
func (UnimplementedGovernanceServer) mustEmbedUnimplementedGovernanceServer() {}
func (UnimplementedGovernanceServer) testEmbeddedByValue()                    {}

// UnsafeGovernanceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GovernanceServer will
// result in compilation errors.
type UnsafeGovernanceServer interface {
	mustEmbedUnimplementedGovernanceServer()
}

func RegisterGovernanceServer(s grpc.ServiceRegistrar, srv GovernanceServer) {
	// If the following call panics, it indicates UnimplementedGovernanceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Governance_ServiceDesc, srv)
}

func _Governance_IssueEphemeralToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IssueTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GovernanceServer).IssueEphemeralToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Governance_IssueEphemeralToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GovernanceServer).IssueEphemeralToken(ctx, req.(*IssueTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Governance_ConsumeEphemeralToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConsumeTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GovernanceServer).ConsumeEphemeralToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Governance_ConsumeEphemeralToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GovernanceServer).ConsumeEphemeralToken(ctx, req.(*ConsumeTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Governance_ZeroizeToolSecrets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ZeroizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GovernanceServer).ZeroizeToolSecrets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Governance_ZeroizeToolSecrets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GovernanceServer).ZeroizeToolSecrets(ctx, req.(*ZeroizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Governance_SubscribeEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GovernanceServer).SubscribeEvents(m, &grpc.GenericServerStream[SubscribeRequest, VaultEventStream]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Governance_SubscribeEventsServer = grpc.ServerStreamingServer[VaultEventStream]

// Governance_ServiceDesc is the grpc.ServiceDesc for Governance service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Governance_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vault.governance.v1.Governance",
	HandlerType: (*GovernanceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IssueEphemeralToken",
			Handler:    _Governance_IssueEphemeralToken_Handler,
		},
		{
			MethodName: "ConsumeEphemeralToken",
			Handler:    _Governance_ConsumeEphemeralToken_Handler,
		},
		{
			MethodName: "ZeroizeToolSecrets",
			Handler:    _Governance_ZeroizeToolSecrets_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeEvents",
			Handler:       _Governance_SubscribeEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "governance.proto",
}
