// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: governance.proto

package governance

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request to issue a new ephemeral token.
type IssueTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenId       string                 `protobuf:"bytes,1,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`       // Unique identifier for this token (caller-generated)
	Plaintext     string                 `protobuf:"bytes,2,opt,name=plaintext,proto3" json:"plaintext,omitempty"`                  // The secret value to wrap (never logged)
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // Session that owns this token
	ToolName      string                 `protobuf:"bytes,4,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`    // Tool that requested this token
	TtlMs         int64                  `protobuf:"varint,5,opt,name=ttl_ms,json=ttlMs,proto3" json:"ttl_ms,omitempty"`            // Time-to-live in milliseconds (e.g. 1800000 = 30 min)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueTokenRequest) Reset() {
	*x = IssueTokenRequest{}
	mi := &file_governance_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueTokenRequest) ProtoMessage() {}

func (x *IssueTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_governance_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueTokenRequest.ProtoReflect.Descriptor instead.
func (*IssueTokenRequest) Descriptor() ([]byte, []int) {
	return file_governance_proto_rawDescGZIP(), []int{0}
}

func (x *IssueTokenRequest) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

func (x *IssueTokenRequest) GetPlaintext() string {
	if x != nil {
		return x.Plaintext
	}
	return ""
}

func (x *IssueTokenRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *IssueTokenRequest) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *IssueTokenRequest) GetTtlMs() int64 {
	if x != nil {
		return x.TtlMs
	}
	return 0
}

// Response from token issuance.
type IssueTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // true if the token was stored successfully
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueTokenResponse) Reset() {
	*x = IssueTokenResponse{}
	mi := &file_governance_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueTokenResponse) ProtoMessage() {}

func (x *IssueTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_governance_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueTokenResponse.ProtoReflect.Descriptor instead.
func (*IssueTokenResponse) Descriptor() ([]byte, []int) {
	return file_governance_proto_rawDescGZIP(), []int{1}
}

func (x *IssueTokenResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Request to consume (redeem) an ephemeral token.
type ConsumeTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenId       string                 `protobuf:"bytes,1,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`       // The token_id to redeem
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // Session that owns this token (must match issuer)
	ToolName      string                 `protobuf:"bytes,3,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`    // Tool consuming this token
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumeTokenRequest) Reset() {
	*x = ConsumeTokenRequest{}
	mi := &file_governance_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumeTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeTokenRequest) ProtoMessage() {}

func (x *ConsumeTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_governance_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeTokenRequest.ProtoReflect.Descriptor instead.
func (*ConsumeTokenRequest) Descriptor() ([]byte, []int) {
	return file_governance_proto_rawDescGZIP(), []int{2}
}

func (x *ConsumeTokenRequest) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

func (x *ConsumeTokenRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ConsumeTokenRequest) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

// Response from token consumption containing the unwrapped plaintext.
type ConsumeTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plaintext     string                 `protobuf:"bytes,1,opt,name=plaintext,proto3" json:"plaintext,omitempty"` // The decrypted secret value
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumeTokenResponse) Reset() {
	*x = ConsumeTokenResponse{}
	mi := &file_governance_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumeTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeTokenResponse) ProtoMessage() {}

func (x *ConsumeTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_governance_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeTokenResponse.ProtoReflect.Descriptor instead.
func (*ConsumeTokenResponse) Descriptor() ([]byte, []int) {
	return file_governance_proto_rawDescGZIP(), []int{3}
}

func (x *ConsumeTokenResponse) GetPlaintext() string {
	if x != nil {
		return x.Plaintext
	}
	return ""
}

// Request to zeroize all secrets for a tool/session pair.
type ZeroizeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToolName      string                 `protobuf:"bytes,1,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`    // Tool whose secrets should be destroyed
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // Session whose secrets should be destroyed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ZeroizeRequest) Reset() {
	*x = ZeroizeRequest{}
	mi := &file_governance_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZeroizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZeroizeRequest) ProtoMessage() {}

func (x *ZeroizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_governance_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZeroizeRequest.ProtoReflect.Descriptor instead.
func (*ZeroizeRequest) Descriptor() ([]byte, []int) {
	return file_governance_proto_rawDescGZIP(), []int{4}
}

func (x *ZeroizeRequest) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *ZeroizeRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// Response from zeroization indicating how many secrets were destroyed.
type ZeroizeResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SecretsDestroyed int32                  `protobuf:"varint,1,opt,name=secrets_destroyed,json=secretsDestroyed,proto3" json:"secrets_destroyed,omitempty"` // Count of secrets securely erased
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ZeroizeResponse) Reset() {
	*x = ZeroizeResponse{}
	mi := &file_governance_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZeroizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZeroizeResponse) ProtoMessage() {}

func (x *ZeroizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_governance_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZeroizeResponse.ProtoReflect.Descriptor instead.
func (*ZeroizeResponse) Descriptor() ([]byte, []int) {
	return file_governance_proto_rawDescGZIP(), []int{5}
}

func (x *ZeroizeResponse) GetSecretsDestroyed() int32 {
	if x != nil {
		return x.SecretsDestroyed
	}
	return 0
}

// Request to subscribe to vault events.
type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // Optional: filter events to this session only
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_governance_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_governance_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_governance_proto_rawDescGZIP(), []int{6}
}

func (x *SubscribeRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// A single event emitted by the vault event stream.
type VaultEventStream struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventType     string                 `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"` // Event kind: "issued", "consumed", "expired", "zeroized"
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // Session that triggered the event
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                 // Event timestamp (Unix milliseconds)
	Payload       string                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`                      // Structured event payload (JSON-encoded)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VaultEventStream) Reset() {
	*x = VaultEventStream{}
	mi := &file_governance_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VaultEventStream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VaultEventStream) ProtoMessage() {}

func (x *VaultEventStream) ProtoReflect() protoreflect.Message {
	mi := &file_governance_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VaultEventStream.ProtoReflect.Descriptor instead.
func (*VaultEventStream) Descriptor() ([]byte, []int) {
	return file_governance_proto_rawDescGZIP(), []int{7}
}

func (x *VaultEventStream) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *VaultEventStream) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *VaultEventStream) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *VaultEventStream) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

var File_governance_proto protoreflect.FileDescriptor

const file_governance_proto_rawDesc = "" +
	"\n" +
	"\x10governance.proto\x12\x13vault.governance.v1\"\x9f\x01\n" +
	"\x11IssueTokenRequest\x12\x19\n" +
	"\btoken_id\x18\x01 \x01(\tR\atokenId\x12\x1c\n" +
	"\tplaintext\x18\x02 \x01(\tR\tplaintext\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12\x1b\n" +
	"\ttool_name\x18\x04 \x01(\tR\btoolName\x12\x15\n" +
	"\x06ttl_ms\x18\x05 \x01(\x03R\x05ttlMs\".\n" +
	"\x12IssueTokenResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"l\n" +
	"\x13ConsumeTokenRequest\x12\x19\n" +
	"\btoken_id\x18\x01 \x01(\tR\atokenId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x1b\n" +
	"\ttool_name\x18\x03 \x01(\tR\btoolName\"4\n" +
	"\x14ConsumeTokenResponse\x12\x1c\n" +
	"\tplaintext\x18\x01 \x01(\tR\tplaintext\"L\n" +
	"\x0eZeroizeRequest\x12\x1b\n" +
	"\ttool_name\x18\x01 \x01(\tR\btoolName\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\">\n" +
	"\x0fZeroizeResponse\x12+\n" +
	"\x11secrets_destroyed\x18\x01 \x01(\x05R\x10secretsDestroyed\"1\n" +
	"\x10SubscribeRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\x88\x01\n" +
	"\x10VaultEventStream\x12\x1d\n" +
	"\n" +
	"event_type\x18\x01 \x01(\tR\teventType\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12\x18\n" +
	"\apayload\x18\x04 \x01(\tR\apayload2\xa6\x03\n" +
	"\n" +
	"Governance\x12f\n" +
	"\x13IssueEphemeralToken\x12&.vault.governance.v1.IssueTokenRequest\x1a'.vault.governance.v1.IssueTokenResponse\x12l\n" +
	"\x15ConsumeEphemeralToken\x12(.vault.governance.v1.ConsumeTokenRequest\x1a).vault.governance.v1.ConsumeTokenResponse\x12_\n" +
	"\x12ZeroizeToolSecrets\x12#.vault.governance.v1.ZeroizeRequest\x1a$.vault.governance.v1.ZeroizeResponse\x12a\n" +
	"\x0fSubscribeEvents\x12%.vault.governance.v1.SubscribeRequest\x1a%.vault.governance.v1.VaultEventStream0\x01B8Z6github.com/armorclaw/bridge/pkg/vault/proto;governanceb\x06proto3"

var (
	file_governance_proto_rawDescOnce sync.Once
	file_governance_proto_rawDescData []byte
)

func file_governance_proto_rawDescGZIP() []byte {
	file_governance_proto_rawDescOnce.Do(func() {
		file_governance_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_governance_proto_rawDesc), len(file_governance_proto_rawDesc)))
	})
	return file_governance_proto_rawDescData
}

var file_governance_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_governance_proto_goTypes = []any{
	(*IssueTokenRequest)(nil),    // 0: vault.governance.v1.IssueTokenRequest
	(*IssueTokenResponse)(nil),   // 1: vault.governance.v1.IssueTokenResponse
	(*ConsumeTokenRequest)(nil),  // 2: vault.governance.v1.ConsumeTokenRequest
	(*ConsumeTokenResponse)(nil), // 3: vault.governance.v1.ConsumeTokenResponse
	(*ZeroizeRequest)(nil),       // 4: vault.governance.v1.ZeroizeRequest
	(*ZeroizeResponse)(nil),      // 5: vault.governance.v1.ZeroizeResponse
	(*SubscribeRequest)(nil),     // 6: vault.governance.v1.SubscribeRequest
	(*VaultEventStream)(nil),     // 7: vault.governance.v1.VaultEventStream
}
var file_governance_proto_depIdxs = []int32{
	0, // 0: vault.governance.v1.Governance.IssueEphemeralToken:input_type -> vault.governance.v1.IssueTokenRequest
	2, // 1: vault.governance.v1.Governance.ConsumeEphemeralToken:input_type -> vault.governance.v1.ConsumeTokenRequest
	4, // 2: vault.governance.v1.Governance.ZeroizeToolSecrets:input_type -> vault.governance.v1.ZeroizeRequest
	6, // 3: vault.governance.v1.Governance.SubscribeEvents:input_type -> vault.governance.v1.SubscribeRequest
	1, // 4: vault.governance.v1.Governance.IssueEphemeralToken:output_type -> vault.governance.v1.IssueTokenResponse
	3, // 5: vault.governance.v1.Governance.ConsumeEphemeralToken:output_type -> vault.governance.v1.ConsumeTokenResponse
	5, // 6: vault.governance.v1.Governance.ZeroizeToolSecrets:output_type -> vault.governance.v1.ZeroizeResponse
	7, // 7: vault.governance.v1.Governance.SubscribeEvents:output_type -> vault.governance.v1.VaultEventStream
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_governance_proto_init() }
func file_governance_proto_init() {
	if File_governance_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_governance_proto_rawDesc), len(file_governance_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_governance_proto_goTypes,
		DependencyIndexes: file_governance_proto_depIdxs,
		MessageInfos:      file_governance_proto_msgTypes,
	}.Build()
	File_governance_proto = out.File
	file_governance_proto_goTypes = nil
	file_governance_proto_depIdxs = nil
}
