version: 2

run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor
    - zig-cache
    - zig-out

linters:
  disable-all: true
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign

linters-settings:
  govet:
    enable-all: true
    disable:
      - shadow

  errcheck:
    check-type-assertions: true
    check-blank: true

  staticcheck:
    checks: ["all"]

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck

