// Package setup provides configuration generation utilities.
// This handles creating TOML configuration files for the bridge.
package setup

import (
	"bytes"
	cryptorand "crypto/rand"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

const (
	// DefaultConfigDir is the default directory for configuration
	DefaultConfigDir = "/etc/armorclaw"

	// DefaultConfigFile is the default configuration filename
	DefaultConfigFile = "config.toml"
)

// BridgeConfig contains all configuration for the ArmorClaw bridge
type BridgeConfig struct {
	// Server settings
	ServerName string
	APIKey     string // Never written to disk, only used for env generation

	// Matrix settings
	MatrixHomeserver string
	MatrixUser       string
	MatrixPassword   string // Never written to disk

	// Bridge settings
	SocketPath string
	LogLevel   string

	// Security settings
	EnableE2EE     bool
	SessionTimeout string

	// Keystore settings
	KeystorePath     string
	KeystorePassword string // Never written to disk

	// SSL settings
	SSLEnabled  bool
	SSLCertPath string
	SSLKeyPath  string
}

// ConfigTemplate is the TOML configuration template
const ConfigTemplate = `# ArmorClaw Bridge Configuration
# Generated by setup wizard
# {{.GeneratedDate}}

[server]
# Server hostname for Matrix federation
server_name = "{{.ServerName}}"

# API key for LLM provider (set via environment variable)
# ARMORCLAW_API_KEY=sk-your-key

[matrix]
# Matrix homeserver URL
homeserver = "{{.MatrixHomeserver}}"

# Bot user credentials (set via environment variables)
# ARMORCLAW_MATRIX_USER=@armorclaw:{{.ServerName}}
# ARMORCLAW_MATRIX_PASSWORD=your-password

[bridge]
# Unix socket path for RPC communication
socket_path = "{{.SocketPath}}"

# Log level: debug, info, warn, error
log_level = "{{.LogLevel}}"

[security]
# Enable end-to-end encryption
enable_e2ee = {{.EnableE2EE}}

# Session timeout for sealed keystore
session_timeout = "{{.SessionTimeout}}"

[keystore]
# Path to encrypted keystore database
path = "{{.KeystorePath}}"

# Keystore encryption key (set via environment variable)
# ARMORCLAW_KEYSTORE_KEY=your-encryption-key

{{if .SSLEnabled}}
[ssl]
# TLS certificate and key paths
enabled = true
cert_path = "{{.SSLCertPath}}"
key_path = "{{.SSLKeyPath}}"
{{end}}
`

// EnvTemplate is the environment variables template
const EnvTemplate = `# ArmorClaw Environment Variables
# Add these to your environment or .env file
# Generated: {{.GeneratedDate}}

# LLM Provider API Key
ARMORCLAW_API_KEY={{.APIKey}}

# Matrix Bot Credentials
ARMORCLAW_MATRIX_USER={{.MatrixUser}}
ARMORCLAW_MATRIX_PASSWORD={{.MatrixPassword}}

# Keystore Encryption Key (generate with: openssl rand -hex 32)
ARMORCLAW_KEYSTORE_KEY={{.KeystorePassword}}
`

// GeneratedConfig contains the generated configuration output
type GeneratedConfig struct {
	ConfigPath string
	ConfigData string
	EnvPath    string
	EnvData    string
}

// GenerateConfig generates configuration from a BridgeConfig
func GenerateConfig(cfg BridgeConfig) (*GeneratedConfig, error) {
	// Set defaults
	if cfg.MatrixHomeserver == "" {
		cfg.MatrixHomeserver = fmt.Sprintf("https://%s:6167", cfg.ServerName)
	}
	if cfg.SocketPath == "" {
		cfg.SocketPath = "/run/armorclaw/bridge.sock"
	}
	if cfg.LogLevel == "" {
		cfg.LogLevel = "info"
	}
	if cfg.SessionTimeout == "" {
		cfg.SessionTimeout = "5m"
	}
	if cfg.KeystorePath == "" {
		cfg.KeystorePath = "/var/lib/armorclaw/keystore.db"
	}
	if cfg.MatrixUser == "" {
		cfg.MatrixUser = fmt.Sprintf("@armorclaw:%s", cfg.ServerName)
	}

	// Prepare template data
	templateData := struct {
		BridgeConfig
		GeneratedDate string
	}{
		BridgeConfig:  cfg,
		GeneratedDate: "Auto-generated by ArmorClaw setup",
	}

	// Generate TOML config
	tmpl, err := template.New("config").Parse(ConfigTemplate)
	if err != nil {
		return nil, WrapError(err, ErrConfigWriteFailed)
	}

	var configBuf bytes.Buffer
	if err := tmpl.Execute(&configBuf, templateData); err != nil {
		return nil, WrapError(err, ErrConfigWriteFailed)
	}

	// Generate environment variables
	envTmpl, err := template.New("env").Parse(EnvTemplate)
	if err != nil {
		return nil, WrapError(err, ErrConfigWriteFailed)
	}

	var envBuf bytes.Buffer
	if err := envTmpl.Execute(&envBuf, templateData); err != nil {
		return nil, WrapError(err, ErrConfigWriteFailed)
	}

	result := &GeneratedConfig{
		ConfigPath: filepath.Join(DefaultConfigDir, DefaultConfigFile),
		ConfigData: configBuf.String(),
		EnvPath:    filepath.Join(DefaultConfigDir, "bridge.env"),
		EnvData:    envBuf.String(),
	}

	return result, nil
}

// WriteConfig writes the configuration to disk
// Note: Environment file is NOT written to disk for security
// The env content should be passed to the user or stored securely
func (g *GeneratedConfig) WriteConfig() error {
	// Create config directory if needed
	if err := os.MkdirAll(DefaultConfigDir, 0755); err != nil {
		return &SetupError{
			Code:  "INS-003",
			Title: "Cannot create config directory",
			Cause: fmt.Sprintf("Failed to create directory %s: %v", DefaultConfigDir, err),
			Fix: []string{
				"Check parent directory permissions",
				"Run with appropriate privileges",
			},
			ExitCode: 1,
		}
	}

	// Write TOML config (without secrets)
	if err := os.WriteFile(g.ConfigPath, []byte(g.ConfigData), 0644); err != nil {
		return &SetupError{
			Code:  "INS-003",
			Title: "Cannot write configuration file",
			Cause: fmt.Sprintf("Failed to write config to %s: %v", g.ConfigPath, err),
			Fix: []string{
				"Check directory permissions",
				"Ensure sufficient disk space",
			},
			ExitCode: 1,
		}
	}

	// DO NOT write environment file to disk
	// It contains secrets and should only be returned to the caller

	return nil
}

// GenerateAndWriteConfig is a convenience function
func GenerateAndWriteConfig(cfg BridgeConfig) (*GeneratedConfig, error) {
	result, err := GenerateConfig(cfg)
	if err != nil {
		return nil, err
	}

	if err := result.WriteConfig(); err != nil {
		return nil, err
	}

	return result, nil
}

// ValidateConfig validates a BridgeConfig before generation
func ValidateConfig(cfg BridgeConfig) error {
	var errors []string

	if cfg.ServerName == "" {
		errors = append(errors, "server_name is required")
	}

	if cfg.ServerName != "" {
		// Basic hostname validation
		if strings.Contains(cfg.ServerName, " ") {
			errors = append(errors, "server_name cannot contain spaces")
		}
		if strings.Contains(cfg.ServerName, "://") {
			errors = append(errors, "server_name should be a hostname, not a URL")
		}
	}

	if cfg.APIKey != "" && len(cfg.APIKey) < 20 {
		errors = append(errors, "api_key should be at least 20 characters")
	}

	if len(errors) > 0 {
		return &SetupError{
			Code:  "INS-005",
			Title: "Invalid configuration",
			Cause: "The configuration contains invalid values:\n  - " + strings.Join(errors, "\n  - "),
			Fix: []string{
				"Review the configuration values",
				"Ensure all required fields are provided",
			},
			ExitCode: 1,
		}
	}

	return nil
}

// ConfigExists checks if a configuration file already exists
func ConfigExists() bool {
	configPath := filepath.Join(DefaultConfigDir, DefaultConfigFile)
	_, err := os.Stat(configPath)
	return err == nil
}

// LoadExistingConfig loads and returns the raw config file content
func LoadExistingConfig() (string, error) {
	configPath := filepath.Join(DefaultConfigDir, DefaultConfigFile)
	data, err := os.ReadFile(configPath)
	if err != nil {
		return "", WrapError(err, ErrConfigWriteFailed)
	}
	return string(data), nil
}

// GenerateRandomPassword generates a secure random password
func GenerateRandomPassword(length int) (string, error) {
	if length < 16 {
		length = 16
	}

	// Use crypto/rand for secure random generation
	const chars = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!@#$%^&*"
	result := make([]byte, length)

	randomBytes := make([]byte, length)
	if _, err := cryptorand.Read(randomBytes); err != nil {
		return "", err
	}

	for i := range length {
		result[i] = chars[int(randomBytes[i])%len(chars)]
	}

	return string(result), nil
}
